import logging
import sys
import os

# Add the project root to Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

from mcp_server.tools.linkedin import LinkedInAPI
from dotenv import load_dotenv, find_dotenv
from common.llm_orchestrator import LLMOrchestrator
from mcp_server.tools.extract_content import ExtractContent
import asyncio

# Configure logging to show detailed information
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def check_api_credentials():
    """Check and log LinkedIn API credential details."""
    client_id = os.getenv('LINKEDIN_CLIENT_ID')
    client_secret = os.getenv('LINKEDIN_CLIENT_SECRET')
    access_token = os.getenv('LINKEDIN_ACCESS_TOKEN')
    person_urn = os.getenv('LINKEDIN_PERSON_URN')
    missing = []
    if not client_id:
        missing.append('LINKEDIN_CLIENT_ID')
    if not client_secret:
        missing.append('LINKEDIN_CLIENT_SECRET')
    if not access_token:
        missing.append('LINKEDIN_ACCESS_TOKEN')
    if not person_urn:
        missing.append('LINKEDIN_PERSON_URN')
    if missing:
        logger.error(f"Missing LinkedIn API credentials: {', '.join(missing)}")
        return False
    logger.info("All LinkedIn API credentials found.")
    return True

async def test_linkedin():
    try:
        # Load environment variables
        dotenv_path = find_dotenv()
        logger.info(f"Loading .env from: {dotenv_path}")
        load_dotenv(dotenv_path)

        # Check API credentials before initialization
        if not check_api_credentials():
            raise ValueError("Invalid LinkedIn API credentials in .env file")

        # Initialize LinkedInAPI, LLM, and ExtractContent
        linkedin = LinkedInAPI()
        llm = LLMOrchestrator(provider="openai")
        extractor = ExtractContent()
        logger.info("LinkedInAPI, LLMOrchestrator, and ExtractContent initialized")

        # Use the provided URL
        url = "https://analytickit.com/the-battle-for-blockchain-dominance-solana-vs-ethereum/"
        logger.info(f"Extracting content from URL: {url}")
        text = await extractor.extract(url)
        if not text:
            raise Exception("Failed to extract content from the URL")

        # Use the same prompt as in post_to_linkedin_node
        prompt = f"""Write a LinkedIn post summary for the following article. Include a call to action. Content: {text}\nLink: {url}"""
        logger.info("Generating LinkedIn summary using LLM...")
        summary = await llm.generate_content(prompt)
        if not summary:
            raise Exception("No summary generated by LLM")

        post_text = f"{summary}\n\nRead more: {url}"
        logger.info("Posting to LinkedIn via API...")
        post_result = linkedin.create_post(post_text)
        logger.info(f"Post creation result: {post_result}")

    except ValueError as e:
        logger.error(f"Configuration error: {str(e)}")
        raise
    except Exception as e:
        logger.error(f"Test failed with error: {str(e)}")
        raise
    finally:
        logger.info("LinkedIn API test complete.")

if __name__ == "__main__":
    try:
        asyncio.run(test_linkedin())
    except KeyboardInterrupt:
        logger.info("Test interrupted by user")
    except Exception as e:
        logger.error(f"Test failed: {str(e)}") 